from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class IRotatorController(Protocol):
    @property
    def is_busy(self) -> bool: ...
    
    def open(self) -> None: ...
    def close(self) -> None: ...
    def request_rotation(self, angle: float) -> None: ...
