from __future__ import annotations
from typing import Protocol, runtime_checkable

from base_core.math.models import Angle


@runtime_checkable
class IRotatorController(Protocol):
    @property
    def is_busy(self) -> bool: ...
    
    def open(self) -> None: ...
    def close(self) -> None: ...
    def request_rotation(self, angle: Angle) -> None: ...
    def request_homing(self) -> None: ...
    def request_set_speed(self, percent: int) -> None: ...
