from __future__ import annotations
from typing import Protocol, runtime_checkable

from base_core.math.models import Angle
from elliptec.config import ELL14Config


@runtime_checkable
class IRotatorController(Protocol):
    @property
    def is_busy(self) -> bool: ...
    @property
    def config(self) -> ELL14Config: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def request_rotation(self, angle: Angle) -> None: ...
    def request_homing(self) -> None: ...
    def request_set_speed(self, percent: int) -> None: ...
    def request_apply_config(self) -> None: ...
